Revert "XDK Heap Profiler collector and XDK CPUProfiler"
This reverts commit 6e8bb75a4232f90de338374e6dd443f06a18feda.

This commit as-is breaks the M51 standalone build:

```
../test/cctest/test-cpu-profiler.cc:1626:29: error: no viable conversion from 'const std::vector<const v8::CpuProfileNode *>' to 'const v8::CpuProfileNode *'
  const v8::CpuProfileNode* start_node = GetChild(env, root, "start");
                            ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../test/cctest/test-cpu-profiler.cc:1628:29: error: no viable conversion from 'const std::vector<const v8::CpuProfileNode *>' to 'const v8::CpuProfileNode *'
  const v8::CpuProfileNode* level2_node = GetChild(env, level1_node, "level2");
                            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../test/cctest/test-profile-generator.cc:291:8: error: no matching member function for call to 'AddPathFromEnd'
  tree.AddPathFromEnd(path_vec);
  ~~~~~^~~~~~~~~~~~~~
.././src/profiler/profile-generator.h:215:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<StackEntry>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
.././src/profiler/profile-generator.h:221:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<CodeEntry *>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
../test/cctest/test-profile-generator.cc:324:8: error: no matching member function for call to 'AddPathFromEnd'
  tree.AddPathFromEnd(path_vec2);
  ~~~~~^~~~~~~~~~~~~~
.././src/profiler/profile-generator.h:215:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<StackEntry>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
.././src/profiler/profile-generator.h:221:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<CodeEntry *>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
```